### ISSUE TITLE
[BUG] UI overflow in x-axis 

### ISSUE THREAD

**Issue by 4F24L** [juspay/hyperswitch#6152] opened 2024-09-28 20:26 UTC
## Issues
- Page overflow in x-axis
- Side scroll wheel [ ugly ui ]
- "Powered by Juspay" - covered under nav bar

### Expected Behavior

- Bottom scroll bar shouldn't be visible
- nav and the "juspay"  div should be separate

### Actual Behavior

See the reference video clip

https://github.com/user-attachments/assets/d04997e1-7e93-4776-b58a-6db87262acdb

### Steps To Reproduce

Some CSS changes may fix this issue.

### Environment

Are you using hyperswitch hosted version? No
If yes, please provide the value of the `x-request-id` response header to help us debug your issue.

If not (or if building/running locally), please provide the following details:
1. Operating System or Linux distribution:
2. Rust version (output of `rustc --version`): ``
3. App version (output of `cargo r --features vergen -- --version`): ``

### Have you spent some time checking if this bug has been raised before?

- [X] I checked and didn't find a similar issue

### Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/juspay/hyperswitch/blob/main/docs/CONTRIBUTING.md)

### Are you willing to submit a PR?

Yes, I am willing to submit a PR!

**Comment by thev19** [comment] 2024-10-02 10:21
@4F24L I would like to work on this.

**Comment by 4F24L** [comment] 2024-10-02 10:34
@thev19 You can work on this.

**Comment by Shivam250702** [comment] 2024-10-02 18:49
hi @4F24L I would like to work on this issue please assign this issue to me

**Comment by gorakhnathy7** [comment] 2024-10-03 05:40
Hey @Shivam250702 , @thev19 is already working on this issue.
Kindly pick another issue from [here](https://github.com/juspay/hyperswitch/issues?q=is%3Aissue+is%3Aopen+no%3Aassignee+label%3Ahacktoberfest)

**Comment by love-sonkar** [comment] 2024-10-03 11:58
@gorakhnathy7 Hey can you guide me how can i find footer page

**Comment by gorakhnathy7** [comment] 2024-10-04 02:47
Hey @love-sonkar this issue is already being worked upon by @thev19 .Kindly pick another issue from [here](https://github.com/juspay/hyperswitch/issues?q=is%3Aissue+is%3Aopen+no%3Aassignee+label%3Ahacktoberfest).

**Comment by love-sonkar** [comment] 2024-10-04 04:26
@gorakhnathy7 i know, i just want to learn the file structure of this repo btw this issue is in wrong repo i guess

**Comment by love-sonkar** [comment] 2024-10-04 04:27
can you guide me how can i find the header and footer of this website

**Comment by 4F24L** [comment] 2024-10-04 08:00
Hey @Shivam250702 , Are you working on this ?!

If not, I can start fixing this . You can assign me @gorakhnathy7

**Comment by gorakhnathy7** [comment] 2024-10-04 09:07
Hey @thev19 Are you still working on this issue?

**Comment by thev19** [comment] 2024-10-04 09:20
Hey @gorakhnathy7, Yes, I am working on this issue.

**Comment by love-sonkar** [comment] 2024-10-04 09:26
@gorakhnathy7 but the issue is in wrong Repo ??

this repo is for backend right

**Comment by gorakhnathy7** [comment] 2024-10-06 03:34
Hey @4F24L Thanks for your concern about this, As mentioned by @thev19 [here](https://github.com/juspay/hyperswitch/issues/6152#issuecomment-2393253910), let's give them some time.
We believe in spirit of Open source, and expect everyone to follow the same, would request @thev19 to let us know, if they won't be able to work on this.
Meanwhile @4F24L, you can pick issues from this [pool](https://github.com/juspay/hyperswitch/issues?q=is%3Aopen+is%3Aissue+label%3Ahacktoberfest+no%3Aassignee)

**Comment by thev19** [comment] 2024-10-06 16:55
@gorakhnathy7 Hey I am working on this, I am facing some issues, I am trying to resolve it. I have posted the issue on slack.

**Comment by gorakhnathy7** [comment] 2024-10-10 07:58
Hey @thev19 and @4F24L While we appreciate the vigilance and efforts here, unfortunately we have not open-sourced the website code, and internal team will get this fixed.

Meanwhile you can check other issues [here](https://github.com/juspay/hyperswitch/issues?q=is%3Aopen+is%3Aissue+label%3Ahacktoberfest+no%3Aassignee)

**Closed by gorakhnathy7** 2024-10-10 07:58 UTC
Labels: C-bug, S-awaiting-triage

**Comment by 4F24L** [comment] 2024-10-10 11:28
Can I work on this ??!

**Comment by gorakhnathy7** [comment] 2024-10-10 19:36
Hey @4F24L as i mentioned the code for this in not open yet, so you can probably pick another issue.
