### ISSUE TITLE
Update the Twitter logo to X

### ISSUE THREAD

**Issue by Shreyas0410** [juspay/hyperswitch#2657] opened 2023-10-20 17:23 UTC
To Reproduce -
Go to the Be a part of community of the website.

In the current version of the website the logo of Twitter is not updated.
![Screenshot 2023-10-20 225132](https://github.com/juspay/hyperswitch/assets/70795867/c526797c-d282-4bcb-8e34-d2fda986303d)

**Comment by Shreyas0410** [comment] 2023-10-20 17:23
Please assign me this issue.

**Comment by SanchithHegde** [comment] 2023-10-22 10:15
This repository does not contain the source code for the website, closing this as invalid. Duplicate of #2499, #2530.

**Closed by SanchithHegde** 2023-10-22 10:15 UTC
