### ISSUE TITLE
[REFACTOR]: [Stax] Remove Default Case Handling

### ISSUE THREAD

**Issue by Sakilmostak** [juspay/hyperswitch#2285] opened 2023-09-22 11:01 UTC
### :memo: Feature Description

- We utilize match statements to make pivotal decisions, such as generating requests based on the payment method type and managing responses received from the connector. 
- These conditions generally go hand in hand with enum variants. 
- Default case is used because a match statement needs to be exhaustive i.e. every variant needs to be covered. 
- So, if all the explicit cases are handled then default is used to handle the rest.
- Each connector have these match statements but many of them don’t provide reference to each variant in their default case, rather a `_` is put to handle all the other cases. 
- This approach carries a risk because developers may inadvertently overlook the need for explicit handling of the new cases.

### :hammer: Possible Implementation

- Instead of relying on a default match case `_`, developers should handle each and every variant explicitly. 
- By doing so, if there are any changes in the future, they can readily assess the impact of their modifications simply by compiling the code.
- You can check this PR for further reference https://github.com/juspay/hyperswitch/pull/1955

:bookmark: Note: All the changes needed should be contained within `hyperswitch/crates/router/src/connector/`

### :package: Have you spent some time checking if this feature request has been raised before?

- [X] I checked and didn't find a similar issue

### :package: Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/juspay/hyperswitch/blob/main/docs/CONTRIBUTING.md)

**Comment by elchead** [comment] 2023-10-09 07:54
I'd like to take this up

**Comment by Sakilmostak** [comment] 2023-10-09 08:05
Sure @elchead , I have assigned this issue to you

**Comment by elchead** [comment] 2023-10-09 08:50
Thanks, I need some help with matching box types. So far, I've omitted them. Can you check the TODO comment inside my change @Sakilmostak?

**Comment by Sakilmostak** [comment] 2023-10-09 11:27
Hey @elchead, I suggest to implement the try_from for each variant of payment_method_data to increase code readability and while implementing try_from, you can dereference the boxed enum and pass the value in the try_from👍. You can take reference from the sample PR provided in this issue on how to implement try_from

**Comment by swangi-kumari** [comment] 2023-10-18 11:33
Hello @elchead ,
Are you still working on this issue?
Please let us know if you need any help:)

**Comment by elchead** [comment] 2023-10-18 11:36
Hi @swangi-kumari, I opened a PR but midway through @prasunna09 said that the issue is already resolved :/ I'm confused how this could happen. I got the ticket assigned and @Sakilmostak helped me clarify what needs to be done.

**Comment by prasunna09** [comment] 2023-10-18 11:48
@elchead I'm extremely sorry for this, there is a small miscommunication between us, we are closing this issue. 
We have similar issues - https://github.com/juspay/hyperswitch/issues/2263. We would be happy to assign you one of these issues.

**Comment by prasunna09** [comment] 2023-10-18 11:48
@elchead I'm extremely sorry for this, there is a small miscommunication between us, we are closing this issue.
We have similar issues - https://github.com/juspay/hyperswitch/issues/2263. We would be happy to assign you one of these issues.

**Closed by prasunna09** 2023-10-18 11:48 UTC
Labels: A-connector-integration, C-feature, good first issue, hacktoberfest
