### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by bhavyajain511** [juspay/hyperswitch#2530] opened 2023-10-10 11:10 UTC
### Bug Description

Old twitter logo appears on hyperswitch hacktoberfest webpage

### Expected Behavior

It should be replaced with the new logo

### Actual Behavior

<img width="837" alt="Screenshot 2023-10-10 at 4 22 40 PM" src="https://github.com/juspay/hyperswitch/assets/114797016/7ed3452c-e4a6-4a74-bfd7-784e29308b4d">

### Steps To Reproduce

Go to https://hyperswitch.io/hacktoberfest

### Environment

Are you using hyperswitch hosted version? Yes/No
If yes, please provide the value of the `x-request-id` response header to help us debug your issue.

If not (or if building/running locally), please provide the following details:
1. Operating System or Linux distribution:
2. Rust version (output of `rustc --version`): ``
3. App version (output of `cargo r --features vergen -- --version`): ``

### Have you spent some time checking if this bug has been raised before?

- [X] I checked and didn't find a similar issue

### Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/juspay/hyperswitch/blob/main/docs/CONTRIBUTING.md)

### Are you willing to submit a PR?

Yes, I am willing to submit a PR!

**Comment by SanchithHegde** [comment] 2023-10-10 11:11
This repository does not contain the source code for the website, closing this as invalid. Duplicate of #2499.

**Closed** 2023-10-10 11:11 UTC
Labels: C-bug, S-awaiting-triage
